# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddTag.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addTage(object):
    def setupUi(self, addTage):
        addTage.setObjectName("addTage")
        addTage.resize(300, 120)
        self.widget = QtWidgets.QWidget(addTage)
        self.widget.setGeometry(QtCore.QRect(90, 70, 195, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.canelButton = QtWidgets.QPushButton(self.widget)
        self.canelButton.setObjectName("canelButton")
        self.horizontalLayout_2.addWidget(self.canelButton)
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.widget1 = QtWidgets.QWidget(addTage)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 166, 24))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tagLabel = QtWidgets.QLabel(self.widget1)
        self.tagLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tagLabel.setObjectName("tagLabel")
        self.horizontalLayout.addWidget(self.tagLabel)
        self.tagField = QtWidgets.QLineEdit(self.widget1)
        self.tagField.setObjectName("tagField")
        self.horizontalLayout.addWidget(self.tagField)

        self.retranslateUi(addTage)
        QtCore.QMetaObject.connectSlotsByName(addTage)

    def retranslateUi(self, addTage):
        _translate = QtCore.QCoreApplication.translate
        addTage.setWindowTitle(_translate("addTage", "Dialog"))
        self.canelButton.setText(_translate("addTage", "Отменить"))
        self.addButton.setText(_translate("addTage", "Сохранить"))
        self.tagLabel.setText(_translate("addTage", "Тег"))
