# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoteEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boldButton = QtWidgets.QPushButton(self.widget)
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout.addWidget(self.boldButton)
        self.italicButton = QtWidgets.QPushButton(self.widget)
        self.italicButton.setObjectName("italicButton")
        self.horizontalLayout.addWidget(self.italicButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.nameField = QtWidgets.QLineEdit(self.widget)
        self.nameField.setObjectName("nameField")
        self.verticalLayout.addWidget(self.nameField)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addTagButton = QtWidgets.QPushButton(self.widget)
        self.addTagButton.setObjectName("addTagButton")
        self.horizontalLayout_3.addWidget(self.addTagButton)
        self.tagLabel = QtWidgets.QLabel(self.widget)
        self.tagLabel.setText("")
        self.tagLabel.setObjectName("tagLabel")
        self.horizontalLayout_3.addWidget(self.tagLabel)
        self.horizontalLayout_3.setStretch(0, 20)
        self.horizontalLayout_3.setStretch(1, 80)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.contentField = QtWidgets.QTextEdit(self.widget)
        self.contentField.setObjectName("contentField")
        self.verticalLayout.addWidget(self.contentField)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.canelButton = QtWidgets.QPushButton(self.widget)
        self.canelButton.setObjectName("canelButton")
        self.horizontalLayout_2.addWidget(self.canelButton)
        self.saveButton = QtWidgets.QPushButton(self.widget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.boldButton.setText(_translate("Dialog", "B"))
        self.italicButton.setText(_translate("Dialog", "I"))
        self.addTagButton.setText(_translate("Dialog", "Добавить тег"))
        self.canelButton.setText(_translate("Dialog", "Отменить"))
        self.saveButton.setText(_translate("Dialog", "Сохранить"))
